version: '2'
services:
  zookeeper-1:
    image: zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
    network_mode: host

  zookeeper-2:
    image: zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-2:22888:23888;zookeeper-2:32888:33888;zookeeper-2:42888:43888
    network_mode: host

  zookeeper-3:
    image: zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-3:22888:23888;zookeeper-3:32888:33888;zookeeper-3:42888:43888
    network_mode: host

#  kafka1:
#    image: abc/kafka:latest
#    hostname: kafka1
#    network_mode: host
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
#    depends_on:
#      - zookeeper-1
#      - zookeeper-2
#      - zookeeper-3
#
#  kafka2:
#    image: abc/kafka:latest
#    hostname: kafka2
#    network_mode: host
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
#    depends_on:
#      - zookeeper-1
#      - zookeeper-2
#      - zookeeper-3
#
#  kafka3:
#    image: abc/kafka:latest
#    hostname: kafka3
#    network_mode: host
#    environment:
#      KAFKA_BROKER_ID: 3
#      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
#    depends_on:
#      - zookeeper-1
#      - zookeeper-2
#      - zookeeper-3